### ISSUE TITLE
Discord embed does not expand on some browsers

### ISSUE THREAD

**Issue by TwistedTwigleg** [TwistedTwigleg/godot-forums-vanilla-plugins#2]
Discovered in [this issue](https://github.com/TwistedTwigleg/vanilla-bootstrap/issues/10) on the theme repository.

Currently the Discord embed widget does not expand on all browsers. This is due to some browsers not having support for the `:hover` media query, which the Discord embed relies on to expand when the mouse is over it.

This would be nice to fix in the future if possible, though right now there is a relatively minor issue.

**Comment by Megalomaniak** [comment]
I think this can be safely considered `wontfix` and closed cause browsers should come around to implement it in due time.

**Comment by TwistedTwigleg** [comment]
Sounds good. We can always reopen the issue and/or find a work around later if needed.
Closing...
